In [71]:
import pandas as pd
import numpy as np

In [72]:
sector_df = pd.read_csv('../data/industry_mappings.csv')
data = pd.read_csv('../data/data_with_open_prices.csv')

In [73]:
sector_df

         symbol                company_name                      sector
0    ABAN.N0000       ABANS ELECTRICALS PLC      Electronics/Appliances
1    AFSL.N0000           ABANS FINANCE PLC      Finance/Rental/Leasing
2     AEL.N0000      ACCESS ENGINEERING PLC  Engineering & Construction
3     ACL.N0000              ACL CABLES PLC         Electrical Products
4    APLA.N0000            ACL PLASTICS PLC      Industrial Specialties
..          ...                         ...                         ...
295  VFIN.N0000        VALLIBEL FINANCE PLC      Finance/Rental/Leasing
296   VLL.N0000              VIDULLANKA PLC          Electric Utilities
297   VLL.X0000              VIDULLANKA PLC          Electric Utilities
298  VONE.N0000            VALLIBEL ONE PLC      Wholesale Distributors
299  VPEL.N0000  VALLIBEL POWER ERATHNA PLC          Electric Utilities

[300 rows x 3 columns]

In [74]:
symbols = np.array(sector_df['symbol'].str.split('.').tolist())[:,0]
suffixes = np.array(sector_df['symbol'].str.split('.').tolist())[:,1]

sector_df['symbol'] = symbols
sector_df['suffix'] = suffixes

In [75]:
sector_df

    symbol                company_name                      sector suffix
0     ABAN       ABANS ELECTRICALS PLC      Electronics/Appliances  N0000
1     AFSL           ABANS FINANCE PLC      Finance/Rental/Leasing  N0000
2      AEL      ACCESS ENGINEERING PLC  Engineering & Construction  N0000
3      ACL              ACL CABLES PLC         Electrical Products  N0000
4     APLA            ACL PLASTICS PLC      Industrial Specialties  N0000
..     ...                         ...                         ...    ...
295   VFIN        VALLIBEL FINANCE PLC      Finance/Rental/Leasing  N0000
296    VLL              VIDULLANKA PLC          Electric Utilities  N0000
297    VLL              VIDULLANKA PLC          Electric Utilities  X0000
298   VONE            VALLIBEL ONE PLC      Wholesale Distributors  N0000
299   VPEL  VALLIBEL POWER ERATHNA PLC          Electric Utilities  N0000

[300 rows x 4 columns]

In [76]:
sector_df.isnull().sum()

symbol          0
company_name    0
sector          4
suffix          0
dtype: int64

# Manually imputing

Manually imputation has been done since only 4 categories missing.

In [77]:
missing_idx = np.array(sector_df[sector_df['sector'].isnull()].index)
sector_df.iloc[missing_idx]

    symbol                           company_name sector suffix
49    CALC  CAL FIVE YEAR CLOSED END FUND (Units)    NaN  U0000
50    CALI     CAL FIVE YEAR OPTIMUM FUND (Units)    NaN  U0000
200   NAVF                NAMAL ACUITY VALUE FUND    NaN  U0000
216    COF              SENFIN SECURITIES LIMITED    NaN  U0000

| Company | Sector |
|---|---|
| CAL FIVE YEAR CLOSED END FUND | Investment Trusts/Mutual Funds |
| CAL FIVE YEAR OPTIMUM FUND | Investment Trusts/Mutual Funds |
| NAMAL ACUITY VALUE FUND | Investment Trusts/Mutual Funds |
| SENFIN SECURITIES LIMITED | Investment Banks/Brokers |

In [78]:
#Manually imputing sectors

sector_df.loc[49,'sector'] = 'Investment Trusts/Mutual Funds'
sector_df.loc[50,'sector'] = 'Investment Trusts/Mutual Funds'
sector_df.loc[200,'sector'] = 'Investment Trusts/Mutual Funds'
sector_df.loc[216,'sector'] = 'Investment Banks/Brokers'

In [79]:
#splitting symbol into two features
symbols = np.array(data['symbol'].str.split('.').tolist())[:,0]
suffixes = np.array(data['symbol'].str.split('.').tolist())[:,1]

data['symbol'] = symbols
data['suffix'] = suffixes

In [80]:
#Create a map
unique_symbols = sector_df['symbol'].unique().tolist()
sector_map = { symbol : sector_df[sector_df['symbol'] == symbol]['sector'].values[0]  for symbol in symbols}

In [81]:
data.head()

  symbol        date   open   high     low   close   volume suffix
0   ABAN  2025-02-03  468.0  485.0  447.50  470.00  10154.0  N0000
1   ABAN  2025-02-05  460.0  460.0  430.00  433.00  14587.0  N0000
2   ABAN  2025-02-06  437.0  475.0  430.00  440.75   5961.0  N0000
3   ABAN  2025-02-07  455.0  470.0  451.00  465.00   2629.0  N0000
4   ABAN  2025-02-10  455.0  468.0  441.75  468.00   1763.0  N0000

In [82]:
#mapping sector by symbol
data['sector'] = data['symbol']
data['sector'] = data['sector'].map(sector_map)
data['symbol'].nunique()

268

In [83]:
data.to_csv('../output/01_sector-data-imputed.csv',index = False)